pep257:
  disable:
    - D203
    - D212
    - D213
    - D214
    - D215
    - D404
    - D405
    - D406
    - D407
    - D408
    - D409
    - D410
    - D411
    - D413
    - D415
    - D416
    - D417

pylint:
  disable:
    # Disable unnecessary else after return as it complains when 
    # returning in an else statement which is often more readable
    - no-else-return
    - too-many-arguments
    - too-many-locals
