#
language: python

os:
  - linux

env:
  global:
    - NO_NET=1

git:
  depth: 10

branches:
  only:
    - master

jobs:
  include:
    - python: 3.7
      dist: xenial

before_install:
  - sudo apt-get install libsnappy-dev

# Install dependencies
install:
  - pip install python-snappy
  - pip install fsspec>=0.3.3
  - pip install dask[dataframe] --upgrade
  - pip install pystore
  - pip install -r requirements.travis.txt
  - pip install -e .
  - pip install --upgrade pip
  - pip install codecov
  - pip install pytest-cov
  - pip install codacy-coverage

# command to run tests
script:
  - py.test ./tests --cov=observations --cov-report=xml

# after_success:
#   - python-codacy-coverage -r coverage.xml
