[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "hydropandas"
dynamic = ["version"]
description = "Module by Artesia for loading observation data into custom DataFrames."
license = { file = "LICENSE" }
readme = "readme.md"
authors = [{ name = "Onno Ebbens", email = "o.ebbens@artesia-water.nl" }]
maintainers = [
        { name = "O.N. Ebbens", email = "o.ebbens@artesia-water.nl" },
        { name = "R. Calje", email = "r.calje@artesia-water.nl" },
        { name = "D.A. Brakenhoff", email = "d.brakenhoff@artesia-water.nl" },
        { name = "M.A. Vonk", email = "m.vonk@artesia-water.nl" },
]
requires-python = ">=3.11"
dependencies = [
        "scipy",
        "pandas",
        "matplotlib",
        "tqdm",
        "requests",
        "geopandas",
        "pyproj",
        "contextily",
        "bokeh",
        "branca",
        "folium",
        "rws-ddlpy",
        "pastastore>=1.10.2",
        "openpyxl"
]
classifiers = [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Other Audience",
        "License :: OSI Approved :: MIT License",
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: 3.14',
        "Operating System :: OS Independent",
        'Topic :: Scientific/Engineering :: Hydrology',
]

[project.urls]
homepage = "https://www.artesia-water.nl"
repository = "https://github.com/artesiawater/hydropandas"
documentation = "https://hydropandas.readthedocs.io/en/stable/"

[project.optional-dependencies]
full = [
        "openpyxl",
        "pastastore",
        "flopy",
        "xarray",
        "netCDF4",
        "lxml",
        "pyarrow",
        "brodata>=0.1.4",
]
rtd = [
        "hydropandas[full]",
        "imod",
        "requests",
        "nbconvert",
        "ipykernel",
        "docutils<0.18",
        "sphinx_rtd_theme",
        "Ipython",
        "nbsphinx",
        "nbsphinx_link",
]
ruffing = ["ruff"]
pytesting = ["hydropandas[full,rtd]", "pytest>=7", "pytest-cov", "pytest-sugar"]
coveraging = ["coverage"]
dev = ["hydropandas[ruffing,pytesting]", "tox"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "hydropandas.version.__version__" }

[tool.setuptools.package-data]
"hydropandas.data" = ["*.json"]
"hydropandas.static" = ["*.html", "*.css"]

[tool.ruff]
line-length = 88
target-version = "py311"
extend-include = ["*.ipynb"]
lint.extend-select = ["I"]
show-fixes = true
fix = true
exclude = ["update_knmi_stations.py", "update_matroos.py", "wiski.py"]
lint.ignore = ["RET504", "DTZ005", "DTZ001", "SIM102", "SIM115", "PERF401"]

[tool.ruff.lint.per-file-ignores]
"knmi.py" = ["E712"]             # see PR 239
"observation.py" = ["RUF012"]
"obs_collection.py" = ["RUF012"]

[tool.pytest.ini_options]
addopts = "--durations=0"
markers = ["slow: mark test as slow."]

[tool.tox]
requires = ["tox>=4"]
env_list = ["ruff", "notebooks", "py{311,312,313,314}"]
pass_env = ["LIZARD_ROTTERDAM_API_KEY"]

[tool.tox.env_run_base]
description = "run unit tests"
extras = ["pytesting"]
commands = [
        [
                "pytest",
                "tests",
                "-m",
                "not slow",
                "--ignore=tests/api",
                "--ignore=tests/notebooks",
        ],
]

[tool.tox.env.bro]
description = "run bro tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_101_bro_api.py"]]

[tool.tox.env.era5]
description = "run era5 tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_109_era5_api.py"]]

[tool.tox.env.ggmn]
description = "run ggmn tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_110_ggmn_api.py"]]

[tool.tox.env.ghcn]
description = "run ghcn tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_108_ghcn_api.py"]]

[tool.tox.env.knmi]
description = "run knmi tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_102_knmi_api.py"]]

[tool.tox.env.matroos]
description = "run matroos tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_107_matroos_api.py"]]

[tool.tox.env.lizard_vitens]
description = "run lizard vitens tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_103_lizard_api_vitens.py"]]

[tool.tox.env.lizard_rotterdam]
description = "run lizard rotterdam tests"
extras = ["pytesting"]
pass_env = ["LIZARD_ROTTERDAM_API_KEY"]
commands = [["pytest", "tests/api/test_106_lizard_api_rotterdam.py"]]

[tool.tox.env.waterconnect]
description = "run waterconnect tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_104_waterconnect_api.py"]]

[tool.tox.env.waterinfo]
description = "run waterinfo tests"
extras = ["pytesting"]
commands = [["pytest", "tests/api/test_105_waterinfo_api.py"]]

[tool.tox.env.notebooks]
description = "run all tests with notebooks and coverage"
extras = ["pytesting", "coveraging"]
pass_env = ["LIZARD_ROTTERDAM_API_KEY"]
commands = [
        [
                "coverage",
                "run",
                "--source=hydropandas",
                "-m",
                "pytest",
                "tests",
        ],
        [
                "coverage",
                "xml",
        ],
]

[tool.tox.env.ruff]
description = "run ruff checks"
base_python = "python3.11"
extras = ["ruffing"]
commands = [
        [
                "ruff",
                "check",
                "--extend-select",
                "I",
        ],
        [
                "ruff",
                "format",
                "--check",
        ],
]
