name: hydropandas

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Test suite with py37-ubuntu
            python: "3.7"
            os: ubuntu-latest
            toxenv: py37
          - name: Test suite with py38-ubuntu
            python: "3.8"
            os: ubuntu-latest
            toxenv: py38
          - name: Test suite with py39-ubuntu
            python: "3.9"
            os: ubuntu-latest
            toxenv: py39
          - name: Test suite with py310-ubuntu
            python: "3.10"
            os: ubuntu-latest
            toxenv: py310
          - name: Test suite with py311-ubuntu
            python: "3.11"
            os: ubuntu-latest
            toxenv: py311
          - name: Formatting with black + isort
            python: "3.9"
            os: ubuntu-latest
            toxenv: format
          - name: Linting with flake8 + ruff
            python: "3.9"
            os: ubuntu-latest
            toxenv: lint
          - name: Test suite for notebooks and coverage
            python: "3.9"
            os: ubuntu-latest
            toxenv: notebooks

    name: ${{ matrix.name }}
    env:
      # Color Output
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # Pytest
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Setup tox environment
        run: tox -e ${{ matrix.toxenv }} --notest

      - name: Test
        run: tox -e ${{ matrix.toxenv }} --skip-pkg-install

      - name: Run codacy-coverage-reporter
        if: ${{ matrix.toxenv == 'notebooks' && github.repository == 'ArtesiaWater/hydropandas' && success() }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
