name: knmi

on:
  push:
    paths:
      - ".github/workflows/Tests_KNMI.yml"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/Tests_KNMI.yml"
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Test knmi api
            python: "3.11"
            toxenv: knmi

    name: ${{ matrix.name }}
    env:
      # Color Output
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # Pytest
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Setup tox environment
        run: tox -e ${{ matrix.toxenv }} --notest

      - name: Test
        run: tox -e ${{ matrix.toxenv }} --skip-pkg-install