name: hydropandas

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Test suite with py313-ubuntu
            python: "3.13"
            toxenv: py313
          - name: Test suite with py312-ubuntu
            python: "3.12"
            toxenv: py312
          - name: Test suite with py310-ubuntu
            python: "3.10"
            toxenv: py310
          - name: Formatting and linting with ruff
            python: "3.11"
            toxenv: ruff
          - name: Notebooks and coverage
            python: "3.11"
            toxenv: notebooks

    name: ${{ matrix.name }}
    env:
      # Color Output
      # Rich (pip)
      FORCE_COLOR: 1
      # Tox
      PY_COLORS: 1
      # Pytest
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Setup tox environment
        run: tox -e ${{ matrix.toxenv }} --notest

      - name: Test
        run: tox -e ${{ matrix.toxenv }} --skip-pkg-install
        
