name: waterconnect

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test waterconnect api
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest

      - name: Run test
        run: |
          pytest tests/api/test_104_waterconnect_api.py
